services:
  db:
    image: mysql:8.0.43
    container_name: webshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ChangeThisRootPass
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshop
      MYSQL_PASSWORD: StrongPass123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro   
volumes:
  mysql_data:
