# docker-compose.yml
services:
  db:
    image: mysql:8.0.43
    container_name: webshop-mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-ChangeThisRootPass}
      MYSQL_DATABASE: ${DB_NAME:-webshop}
      MYSQL_USER: ${DB_USER:-webshop}
      MYSQL_PASSWORD: ${DB_PASS:-StrongPass123!}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
